#!/bin/bash

source ${OPENSHIFT_HOMEDIR}python-2.6/virtenv/bin/activate
 
export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python-2.6/virtenv/lib/python-2.6/site-packages
 
echo "Executing 'python ${OPENSHIFT_REPO_DIR}osmdemo/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/osmdemo/manage.py syncdb --noinput
 
echo "Executing 'python ${OPENSHIFT_REPO_DIR}osmdemo/manage.py dataload summitdemo'"
python "$OPENSHIFT_REPO_DIR"wsgi/osmdemo/manage.py dataload summitdemo
